default[:ghost][:user] = "ghost"
default[:ghost][:databag] = nil
default[:ghost][:databag_secret] = nil
default[:ghost][:databag_item] = "secrets"
default[:ghost][:home_dir] = ::File.join("/home", node[:ghost][:user])
default[:ghost][:db_host] = "127.0.0.1"
default[:ghost][:db_name] = "ghost"
default[:ghost][:db_user] = "ghost"
default[:ghost][:db_admin_user] = "root"
default[:ghost][:db_grant_host] = "127.0.0.1"
default[:ghost][:db_client] = 'sqlite3'
default[:ghost][:sqlite3][:db_path] = "/content/data"
default[:ghost][:storage][:dir] = "/content/storage"
default[:ghost][:storage][:location] = "ghost"
default[:ghost][:domain] = "myblog.com"
default[:ghost][:url] = "https://myblog.com"
default[:ghost][:install_base] = '/var/www/vhosts'
default[:ghost][:install_path] = ::File.join(node[:ghost][:install_base], node[:ghost][:domain])
default[:ghost][:storage][:path] = ::File.join(node[:ghost][:install_path], 'ghost', node[:ghost][:storage][:dir])
default[:ghost][:log_dir] = "/var/log/ghost"
default[:ghost][:src_url] = "https://ghost.org/zip/ghost-0.6.4.zip"
default[:ghost][:archive_name] = "ghost.zip"
default[:ghost][:mail_transport] = "local"
default[:ghost][:mail_user] = nil
default[:ghost][:mail_password] = nil
default[:ghost][:node_env] = "development"
default[:ghost][:ssl_cert_path] = "/etc/ssl/certs"
default[:ghost][:ssl_key_path] = "/etc/ssl/private"
default[:ghost][:ssl_cacert_path] = "/etc/ssl/certs"
default[:ghost][:themes] = {}
default[:ghost][:nginx][:additional_config] = ''
